[package]
name = "greeting"
version = "0.1.0"
authors = ["hchc32 <1844382037@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
